<?php

/*
| Authentication tunables (PROJECT_CONSTITUTION R-SEC-02..08; Tech Spec §15).
| Loaded by AppServiceProvider's nested-config loader → config('domain.auth.*').
| Signing keys: prefer PEM content from env (production secret store); fall back
| to the on-disk pair generated by `php artisan auth:generate-keys` (dev/test).
*/
return [

    'issuer' => env('AUTH_JWT_ISSUER', 'salam-hayetimiz'),

    // Access-token (RS256) parameters per audience. `kid` is published in the header
    // and (for admin) at /.well-known/jwks.json; two kids may be valid during rotation.
    'access' => [
        'user' => [
            'kid' => env('AUTH_JWT_USER_KID', 'user-2026-q2'),
            'ttl_seconds' => 900,   // 15 min (R-SEC-02)
            'audience' => 'salam-mobile',
        ],
        'admin' => [
            'kid' => env('AUTH_JWT_ADMIN_KID', 'admin-2026-q2'),
            'ttl_seconds' => 1800,  // 30 min (R-SEC-05)
            'audience' => 'salam-admin',
        ],
    ],

    // RSA keypairs. env content wins (prod); otherwise the storage/keys/*.pem files.
    'keys' => [
        'user' => [
            'private' => env('AUTH_JWT_USER_PRIVATE_KEY'),
            'public' => env('AUTH_JWT_USER_PUBLIC_KEY'),
            'private_path' => storage_path('keys/jwt_user_private.pem'),
            'public_path' => storage_path('keys/jwt_user_public.pem'),
        ],
        'admin' => [
            'private' => env('AUTH_JWT_ADMIN_PRIVATE_KEY'),
            'public' => env('AUTH_JWT_ADMIN_PUBLIC_KEY'),
            'private_path' => storage_path('keys/jwt_admin_private.pem'),
            'public_path' => storage_path('keys/jwt_admin_public.pem'),
        ],
    ],

    // Two-phase admin login: the challenge JWT (admin key, purpose claim) bridging
    // step 1 (password) and step 2 (TOTP / recovery code).
    'challenge' => [
        'ttl_seconds' => 300, // 5 min
    ],

    // Opaque refresh token (SHA-256 hashed, rotated on each use — R-SEC-02).
    'refresh' => [
        'ttl_days' => 60,
        'bytes' => 32,
    ],

    // SMS OTP (R-SEC-03). Rate limits are enforced by the route limiters (R-SEC-16).
    'otp' => [
        'ttl_seconds' => 120,
        'resend_seconds' => 30,
        'length' => 6,
        'max_attempts' => 5,
    ],

    // Admin password login lockout (R-SEC-16 / Tech Spec §15.2).
    'admin_login' => [
        'max_failed' => 5,
        'lockout_minutes' => 15,
    ],

    // Single-use recovery codes (R-SEC-06): 8 codes, 10 hex chars (5 random bytes).
    'recovery_codes' => [
        'count' => 8,
        'length_bytes' => 5,
    ],

    // TOTP (RFC 6238 — R-SEC-05).
    'totp' => [
        'period' => 30,
        'digits' => 6,
        'algorithm' => 'sha1',
        'window' => 1, // accept ±1 step for clock drift
    ],

    // Retention sweep (auth:prune) — expired/old artifacts.
    'retention' => [
        'auth_attempts_days' => 90,
        'revoked_refresh_tokens_days' => 30,
    ],

];
