// Frontend mirror of the backend permission keys actually referenced by the UI (menu + buttons + routes).
// The backend (App\Domain\Admin\Authorization\Permission) is the source of truth; these are a typed subset.
export const PERM = {
  dashboardView: 'dashboard.view',
  devicesView: 'devices.view',
  devicesCreate: 'devices.create',
  devicesUpdate: 'devices.update',
  devicesReconcile: 'devices.reconcile',
  devicesDisable: 'devices.disable',
  devicesDecommission: 'devices.decommission',
  devicesTransfer: 'devices.transfer',
  devicesAssign: 'devices.assign',
  devicesDiagnostics: 'devices.diagnostics.view',
  whitelistView: 'whitelist.view',
  whitelistManage: 'whitelist.manage',
  commandsView: 'commands.view',
  commandsTest: 'commands.test',
  visitorLinksView: 'visitor_links.view',
  visitorLinksManage: 'visitor_links.manage',
  residentsView: 'residents.view',
  residentsCreate: 'residents.create',
  residentsDelete: 'residents.delete',
  ordersView: 'orders.view',
  paymentsView: 'payments.view',
  refundsView: 'refunds.view',
  refundsCreate: 'refunds.create',
  subscriptionsView: 'subscriptions.view',
  subscriptionsManage: 'subscriptions.manage',
  adminsView: 'admins.view',
  adminsCreate: 'admins.create',
  adminsImpersonate: 'admins.impersonate',
  auditView: 'audit.view',
  systemSettings: 'system.settings.manage',
  accessManage: 'access.manage',
  complexesView: 'complexes.view',
  complexesManage: 'complexes.manage',
  notificationsView: 'notifications.view',
  notificationsSend: 'notifications.send',
} as const
